### PR TITLE
Developer experience fixes

### LINKED ISSUE #1258: Bug: npm start script does not reload on save
## Summary
The `npm start` cli script does not watch for changes and reload the browser as expected.

### Expected result
When `npm start` script is running in the terminal:
- Editing a source file (`.njk`, `.md`, `.js`, `.scss`, etc) triggers a browser reload

### Actual result
When `npm start` script is running in the terminal:
- Editing a source file (`.njk`, `.md`, `.js`, `.scss`, etc) **does not trigger** a browser reload

### Additional Information
Might have been introduced in my work in #1249 :(

### PR DESCRIPTION
**Pull request by mxmason**
## Summary
- Closes #1258
- Adds some developer experience improvements through better incremental builds (see comments)

## Test plan
1. Run `npm start` in the terminal
2. Edit a source file (`.njk`, `.md`, `.js`, `.scss`)
3. Verify that the appropriate watch script is triggered and the browser reloads

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -105,7 +105,7 @@ var buildScripts = function (done) {
 	if (!settings.polyfills) {
 		scriptSrc.push('!' + paths.scripts.polyfills);
 	}
-	return src(scriptSrc)
+	return src(scriptSrc, { since: lastRun(buildScripts) })
```
Comment (mxmason) [inline gulpfile.js:108]: 🔍 `lastRun` allows Gulp to only source files that have changed since the last run of the provided function. In this case, `buildScripts` will only minify and copy .js files that have changed since last build.

File: gulpfile.js [hunk 2]
```diff
@@ -182,7 +181,8 @@ var buildStyles = function (done) {
 				removeAll: true
 			}
 		}))
-		.pipe(dest(paths.styles.output));
+		.pipe(dest(paths.styles.output))
+		.pipe(browserSync.stream());
```
Comment (mxmason) [inline gulpfile.js:185]: 🔍 using `.stream()` allows the browser to render the compiled css without fully reloading

File: gulpfile.js [hunk 3]
```diff
@@ -267,30 +266,31 @@ var reloadBrowser = function (done) {
...
-	watch(paths.input, series(exports.default, reloadBrowser));
-	done();
+var watchSource = function() {
+	watch(paths.styles.input, styles);
+	watch(paths.scripts.input, series(scripts, reloadBrowser));
+	watch(paths.images.input, series(processImages, reloadBrowser));
+	watch(paths.icons.input, series(processIcons, reloadBrowser));
+	watch(paths.svgs.input, series(buildSVGs, reloadBrowser));
+	watch('./dist/**/*.html', reloadBrowser);
 };
```
Comment (mxmason) [inline gulpfile.js:280]: 🔍 Although this is more verbose than the previous watch script, it makes rebuilds more incremental. Changes to `.js` files, for instance, will only trigger a script rebuild, rather than rebuilding every source type in the project

Note: We don't run `reloadBrowser` on style changes because `.stream()` sends the css to the browser as it compiles.

**Review by mxmason — COMMENTED** [review]
Some comments to explain my work 🙇🏻

**Review by SaptakS — APPROVED** [review]
lgtm
